### ISSUE TITLE
can't create or open DB

### ISSUE THREAD

**Issue by shadylabs** [Wiladams/LJIT2Sophia#1]
Same error from my code and from the "test_sophia" example
/sophia.lua:136: cannot convert 'number' to 'void *'
stack traceback:
    [C]: in function 'open'
    ./sophia.lua:136: in function 'SophiaDatabase'
    /home/stampio/frontend/test_sophia.lua:20: in main chunk

There is something unclear with the database directory and the db name . trying to debug but no luck so far.
Latest Sophia ver.

Any help?

**Comment by Wiladams** [comment]
The binding is a work in progress.  So, no help yet.

Sent from my Windows Phone

**Comment by shadylabs** [comment]
ok.
